//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatAiClient.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChatAiClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Cancel {
            get {
                object obj = ResourceManager.GetObject("Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Icon Customer_256 {
            get {
                object obj = ResourceManager.GetObject("Customer_256", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   {0}は存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExistErrorMessage {
            get {
                return ResourceManager.GetString("ExistErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap File {
            get {
                object obj = ResourceManager.GetObject("File", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   &lt;/body&gt;
        ///&lt;/html&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string footer_txt {
            get {
                return ResourceManager.GetString("footer_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge, chrome=1&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string header_txt {
            get {
                return ResourceManager.GetString("header_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputErrorMessage {
            get {
                return ResourceManager.GetString("InputErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   multipart/form-data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelAudioContentType {
            get {
                return ResourceManager.GetString("ModelAudioContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   音声 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelAudioDisplayName {
            get {
                return ResourceManager.GetString("ModelAudioDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   whisper-1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelAudioParamValue {
            get {
                return ResourceManager.GetString("ModelAudioParamValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   v1/audio/transcriptions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelAudioUrlPass {
            get {
                return ResourceManager.GetString("ModelAudioUrlPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   application/json に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelChatContentType {
            get {
                return ResourceManager.GetString("ModelChatContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チャット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelChatDisplayName {
            get {
                return ResourceManager.GetString("ModelChatDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   gpt-3.5-turbo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelChatParamValue {
            get {
                return ResourceManager.GetString("ModelChatParamValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   v1/chat/completions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ModelChatUrlPass {
            get {
                return ResourceManager.GetString("ModelChatUrlPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送信をキャンセルしました。再度質問する場合は質問内容を入力し、送信ボタンを押してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NavigationMessageCancel {
            get {
                return ResourceManager.GetString("NavigationMessageCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラーが発生しました。ログファイルにてエラー内容をご確認ください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NavigationMessageError {
            get {
                return ResourceManager.GetString("NavigationMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   例外が発生しました。ログファイルにてエラー内容をご確認ください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NavigationMessageException {
            get {
                return ResourceManager.GetString("NavigationMessageException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   質問内容を入力し、送信ボタンを押してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NavigationMessageInit {
            get {
                return ResourceManager.GetString("NavigationMessageInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   質問内容を送信中。回答を受信するまでお待ちください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NavigationMessageSubmission {
            get {
                return ResourceManager.GetString("NavigationMessageSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回答内容をご確認ください。再度質問する場合は質問内容を入力し、送信ボタンを押してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NavigationMessageSuccess {
            get {
                return ResourceManager.GetString("NavigationMessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   continue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RequestContinueText {
            get {
                return ResourceManager.GetString("RequestContinueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Submit {
            get {
                object obj = ResourceManager.GetObject("Submit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
